### ISSUE TITLE
STyper module not working in dev

### ISSUE THREAD

**Issue by lgessler** [gucorpling/amalgum#9]
Getting an error when running the pipeline with normal deps:

```
ERROR:root:Encountered an error while processing file target/05_STyper/xml/autogum_academic_doc010.xml!
  0%|                                                                                                                                                                                                                                                                                                   | 0/1 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "nlp_controller.py", line 216, in <module>
    main()
  File "nlp_controller.py", line 211, in main
    controller.run()
  File "nlp_controller.py", line 130, in run
    module.run(input_dir, output_dir)
  File "/home/luke/Sync/playground/amalgum/nlp_modules/xrenner_coreferencer.py", line 66, in run
    input_dir, output_dir, processing_function
  File "/home/luke/Sync/playground/amalgum/nlp_modules/base.py", line 226, in process_files_multiformat
    process_filename(filename)
  File "/home/luke/Sync/playground/amalgum/nlp_modules/base.py", line 203, in process_filename
    raise e
  File "/home/luke/Sync/playground/amalgum/nlp_modules/base.py", line 200, in process_filename
    output_dict = process_document_content_dict(content_dict)
  File "/home/luke/Sync/playground/amalgum/nlp_modules/xrenner_coreferencer.py", line 55, in resolve_entities_coref
    tsv_output = self.xrenner.analyze(doc_dict["dep"], "webannotsv")
  File "/home/luke/.anaconda3/envs/amalgum-test/lib/python3.7/site-packages/xrenner/modules/xrenner_xrenner.py", line 159, in analyze
    seq_preds = lex.sequencer.predict_proba(s_texts)
  File "/home/luke/.anaconda3/envs/amalgum-test/lib/python3.7/site-packages/xrenner/modules/xrenner_sequence.py", line 265, in predict_proba
    preds = self.tagger.predict(sentences)
  File "/home/luke/.anaconda3/envs/amalgum-test/lib/python3.7/site-packages/flair/models/sequence_tagger_model.py", line 358, in predict
    feature: torch.Tensor = self.forward(batch)
  File "/home/luke/.anaconda3/envs/amalgum-test/lib/python3.7/site-packages/flair/models/sequence_tagger_model.py", line 498, in forward
    self.embeddings.embed(sentences)
  File "/home/luke/.anaconda3/envs/amalgum-test/lib/python3.7/site-packages/flair/embeddings.py", line 177, in embed
    embedding.embed(sentences)
  File "/home/luke/.anaconda3/envs/amalgum-test/lib/python3.7/site-packages/flair/embeddings.py", line 96, in embed
    self._add_embeddings_internal(sentences)
  File "/home/luke/.anaconda3/envs/amalgum-test/lib/python3.7/site-packages/flair/embeddings.py", line 2318, in _add_embeddings_internal
    for sentence in sentences
  File "/home/luke/.anaconda3/envs/amalgum-test/lib/python3.7/site-packages/flair/embeddings.py", line 2318, in <listcomp>
    for sentence in sentences
  File "/home/luke/.anaconda3/envs/amalgum-test/lib/python3.7/site-packages/transformers/tokenization_utils.py", line 357, in tokenize
    tokenized_text = split_on_tokens(no_split_token, text)
  File "/home/luke/.anaconda3/envs/amalgum-test/lib/python3.7/site-packages/transformers/tokenization_utils.py", line 351, in split_on_tokens
    for token in tokenized_text
  File "/home/luke/.anaconda3/envs/amalgum-test/lib/python3.7/site-packages/transformers/tokenization_utils.py", line 351, in <genexpr>
    for token in tokenized_text
  File "/home/luke/.anaconda3/envs/amalgum-test/lib/python3.7/site-packages/transformers/tokenization_bert.py", line 219, in _tokenize
    for token in self.basic_tokenizer.tokenize(text, never_split=self.all_special_tokens):
  File "/home/luke/.anaconda3/envs/amalgum-test/lib/python3.7/site-packages/transformers/tokenization_bert.py", line 416, in tokenize
    elif self.strip_accents:
AttributeError: 'BasicTokenizer' object has no attribute 'strip_accents'
```

To reproduce:

```
git clone git@github.com:gucorpling/amalgum.git
cd amalgum
git checkout dev
conda create --name amalgum-test python=3.7
pip install -r requirements.txt
python nlp_controller.py target -i out_one
```

**Comment by lgessler** [comment]
My hunch is that this must be some incompatibility between `transformers` and our old version of `flair==0.4.5`. The issue goes away when I run this again on `flair==0.6.1` (latest).

However, that leads to another issue from Xrenner:

```
ERROR:root:Encountered an error while processing file target/05_STyper/xml/autogum_academic_doc010.xml!
  0%|                                                                                                                                                                                                                                                                                                   | 0/1 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "nlp_controller.py", line 216, in <module>
    main()
  File "nlp_controller.py", line 211, in main
    controller.run()
  File "nlp_controller.py", line 130, in run
    module.run(input_dir, output_dir)
  File "/home/luke/Sync/playground/amalgum/nlp_modules/xrenner_coreferencer.py", line 66, in run
    input_dir, output_dir, processing_function
  File "/home/luke/Sync/playground/amalgum/nlp_modules/base.py", line 226, in process_files_multiformat
    process_filename(filename)
  File "/home/luke/Sync/playground/amalgum/nlp_modules/base.py", line 203, in process_filename
    raise e
  File "/home/luke/Sync/playground/amalgum/nlp_modules/base.py", line 200, in process_filename
    output_dict = process_document_content_dict(content_dict)
  File "/home/luke/Sync/playground/amalgum/nlp_modules/xrenner_coreferencer.py", line 55, in resolve_entities_coref
    tsv_output = self.xrenner.analyze(doc_dict["dep"], "webannotsv")
  File "/home/luke/.anaconda3/envs/amalgum-test/lib/python3.7/site-packages/xrenner/modules/xrenner_xrenner.py", line 159, in analyze
    seq_preds = lex.sequencer.predict_proba(s_texts)
  File "/home/luke/.anaconda3/envs/amalgum-test/lib/python3.7/site-packages/xrenner/modules/xrenner_sequence.py", line 265, in predict_proba
    preds = self.tagger.predict(sentences)
  File "/home/luke/.anaconda3/envs/amalgum-test/lib/python3.7/site-packages/flair/models/sequence_tagger_model.py", line 364, in predict
    batch = self._filter_empty_sentences(batch)
  File "/home/luke/.anaconda3/envs/amalgum-test/lib/python3.7/site-packages/flair/models/sequence_tagger_model.py", line 954, in _filter_empty_sentences
    filtered_sentences = [sentence for sentence in sentences if sentence.tokens]
  File "/home/luke/.anaconda3/envs/amalgum-test/lib/python3.7/site-packages/flair/models/sequence_tagger_model.py", line 954, in <listcomp>
    filtered_sentences = [sentence for sentence in sentences if sentence.tokens]
AttributeError: 'str' object has no attribute 'tokens'
```

**Comment by amir-zeldes** [comment]
Ugh, they keep changing their sentence objects. I don't have bandwidth to fix this ATM, but this where - I already patched it to support flair 0.4.4, 0.4.5 and above up to 0.5 by doing this:

https://github.com/amir-zeldes/xrenner/blob/master/xrenner/modules/xrenner_sequence.py#L238-L242

I guess we now need to catch the case that the Sentence API is different, but note that the pretrained flair model that comes with xrenner's English package will no longer work with 0.6.1, so we'll also need a new model.

**Comment by amir-zeldes** [comment]
So, if I retrain xrenner's sequence labeler with flair 0.6.1, would we be able to resolve this? Let me know and I can do that, I have the training setup ready on my PC (assuming 0.6.1's Bert base still fits into my GPU, otherwise need to set this up in the cluster)

**Comment by lgessler** [comment]
Yeah, I think this will be resolved if the xrenner package is upgraded to flair 0.6.1 and we get a new model trained for flair 0.6.1.

**Comment by amir-zeldes** [comment]
OK, getting to this now - xrenner requirements only says flair>=0.44 (which is admittedly not really right), but that being the case right now, it sounds like I can just replace the model file on corpling, no? Later I should also update reqs to a fixed flair and redeploy to PyPI, but I only want to do that once we're positive we have all the versions nailed down.

**Comment by amir-zeldes** [comment]
The 0.6.1 model is now on corpling where xrenner expects it, and I've updated xrenner to support flair 0.6.1, and deployed on PyPI (turns out the API changes to flair were truly incompatible, so model update was not enough). The new release also updates the entity boundary definition to match GUM V6.2.0, incl. clauses etc.

Does this resolve the current issue? Do we need to retrain other sequence labelers/adapt other modules to flair 0.6.1?

**Comment by lgessler** [comment]
I'm getting the same error after uninstalling xrenner, removing `/.../<python>/site-packages/xrenner/models/` (to force a re-download of the model), installing xrenner and `flair==0.6.1`, and having it automatically download the model from `https://corpling.uis.georgetown.edu/amir/download/eng_flair_nner_distilbert.pt`. I don't think I totally have a handle on all the artifacts involved here, but yes, if there are other serialized models involved, we should retrain them using the new package versions. Are there other serialized models involved aside from `eng_flair_nner_distilbert.pt`?

**Comment by amir-zeldes** [comment]
I can understand the same/similar error is being triggered by another module using flair, but are you positive you're getting the same error triggered by xrenner? Can you paste the trace? xrenner should now be getting past the problem by converting the list of input tokens to flair into Sentence objects, since in flair>=0.6 they want that as input:

https://github.com/amir-zeldes/xrenner/commit/06e82c64dd76cd543fb4d57c187ebda42edc58de#diff-d0b45fec878030d662d341d31c121af425d59852fdaa8f1b2698db2af0aa637bR230

If it's still xrenner throwing the error I'd like to look at the exact logic landing it in the wrong if-else condition.

Other stuff I can imagine needs retraining (maybe API fixing):
  * flair input models to ensemble POS tagger
  * flair sentence splitter
  * flair RST segmenter
  * RST-DT sequence labeler (feature input to RST parser)

I can look at the bottom 3 but I don't know the first one well - @shabnam-b can you take a look at the Amalgum POS tagger inputs and adapt them to run with flair 0.6.1? Probably the models need to be retrained, and it's possible the input list of sentences to be classified needs to be converted from strings to flair.data Sentence objects (not sure, it might depend on how you implemented predict)

**Comment by lgessler** [comment]
here's my trace:

```
INFO:root:Running module XrennerCoref
  0%|                                                                                                                                                                                                                                             | 0/1 [00:00<?, ?it/sERROR:root:Encountered an error while processing file target/06_STyper/xml/autogum_academic_doc010.xml!                                                                                                                                            | 0/1 [00:00<?, ?it/s]
  0%|                                                                                                                                                                                                                                             | 0/1 [00:00<?, ?it/s]
  File "nlp_controller.py", line 220, in <module>
    main()
  File "nlp_controller.py", line 215, in main
    controller.run()
  File "nlp_controller.py", line 132, in run
    module.run(input_dir, output_dir)
  File "/home/luke/Sync/playground/amalgum/nlp_modules/xrenner_coreferencer.py", line 65, in run
    input_dir, output_dir, processing_function
  File "/home/luke/Sync/playground/amalgum/nlp_modules/base.py", line 257, in process_files_multiformat
    process_filename(filename)
  File "/home/luke/Sync/playground/amalgum/nlp_modules/base.py", line 230, in process_filename
    raise e
  File "/home/luke/Sync/playground/amalgum/nlp_modules/base.py", line 227, in process_filename
    output_dict = process_document_content_dict(content_dict)
  File "/home/luke/Sync/playground/amalgum/nlp_modules/xrenner_coreferencer.py", line 54, in resolve_entities_coref
    tsv_output = self.xrenner.analyze(doc_dict["dep"], "webannotsv")
  File "/home/luke/.anaconda3/envs/amalgum-test/lib/python3.7/site-packages/xrenner/modules/xrenner_xrenner.py", line 163, in analyze
    seq_preds = lex.sequencer.predict_proba(s_texts)
  File "/home/luke/.anaconda3/envs/amalgum-test/lib/python3.7/site-packages/xrenner/modules/xrenner_sequence.py", line 304, in predict_proba
    preds = self.tagger.predict(sentences)
  File "/home/luke/.anaconda3/envs/amalgum-test/lib/python3.7/site-packages/flair/models/sequence_tagger_model.py", line 369, in predict
    feature = self.forward(batch)
  File "/home/luke/.anaconda3/envs/amalgum-test/lib/python3.7/site-packages/flair/models/sequence_tagger_model.py", line 624, in forward
    self.embeddings.embed(sentences)
  File "/home/luke/.anaconda3/envs/amalgum-test/lib/python3.7/site-packages/flair/embeddings/token.py", line 71, in embed
    embedding.embed(sentences)
  File "/home/luke/.anaconda3/envs/amalgum-test/lib/python3.7/site-packages/flair/embeddings/base.py", line 60, in embed
    self._add_embeddings_internal(sentences)
  File "/home/luke/.anaconda3/envs/amalgum-test/lib/python3.7/site-packages/flair/embeddings/legacy.py", line 1197, in _add_embeddings_internal
    for sentence in sentences
  File "/home/luke/.anaconda3/envs/amalgum-test/lib/python3.7/site-packages/flair/embeddings/legacy.py", line 1197, in <listcomp>
    for sentence in sentences
  File "/home/luke/.anaconda3/envs/amalgum-test/lib/python3.7/site-packages/transformers/tokenization_utils.py", line 352, in tokenize
    tokenized_text = split_on_tokens(no_split_token, text)
  File "/home/luke/.anaconda3/envs/amalgum-test/lib/python3.7/site-packages/transformers/tokenization_utils.py", line 346, in split_on_tokens
    for token in tokenized_text
  File "/home/luke/.anaconda3/envs/amalgum-test/lib/python3.7/site-packages/transformers/tokenization_utils.py", line 346, in <genexpr>
    for token in tokenized_text
  File "/home/luke/.anaconda3/envs/amalgum-test/lib/python3.7/site-packages/transformers/tokenization_bert.py", line 224, in _tokenize
    for token in self.basic_tokenizer.tokenize(text, never_split=self.all_special_tokens):
  File "/home/luke/.anaconda3/envs/amalgum-test/lib/python3.7/site-packages/transformers/tokenization_bert.py", line 413, in tokenize
    elif self.strip_accents:
AttributeError: 'BasicTokenizer' object has no attribute 'strip_accents'
  0%|      
```

relevant deps:

```
$ conda env export | grep -P "tokenizers|flair|transformers|xrenner"
    - flair==0.6.1
    - tokenizers==0.9.3
    - transformers==3.5.1
    - xrenner==2.2.0.0
```

**Comment by lgessler** [comment]
FWIW the POS tagging module still works fine on `flair==0.6.1`, though in general if we're committed to maintaining this pipeline we should probably work on a centralized way to re-train all our modules in situations like this, maybe by keeping all the training code in a central directory on the CLI GCP GPU boxes and writing some glue code for versioning and publishing the trained models to corpling

**Comment by amir-zeldes** [comment]
That trace actually looks like a different error, this time in transformers, not flair. Looking at my environment I think this is because I have transformers==3.0.2, under which the model on corpling was trained. Oddly flair didn't complain about this, and xrenner is running fine on my machine with 0.6.1... Instead I get stuck on stanfordnlp:

```
  0%|                                                                                                                                                                             | 0/4 [00:00<?, ?it/s] Traceback (most recent call last):
  File "nlp_controller.py", line 220, in <module>
    main()
  File "nlp_controller.py", line 215, in main
    controller.run()
  File "nlp_controller.py", line 132, in run
    module.run(input_dir, output_dir)
  File "C:\Uni\Corpora\GUM\autogum\autogum.git\nlp_modules\dep_parser.py", line 154, in run
    self.process_files_multiformat(input_dir, output_dir, processing_function)
  File "C:\Uni\Corpora\GUM\autogum\autogum.git\nlp_modules\base.py", line 257, in process_files_multiformat
    process_filename(filename)
  File "C:\Uni\Corpora\GUM\autogum\autogum.git\nlp_modules\base.py", line 230, in process_filename
    raise e
  File "C:\Uni\Corpora\GUM\autogum\autogum.git\nlp_modules\base.py", line 227, in process_filename
    output_dict = process_document_content_dict(content_dict)
  File "C:\Uni\Corpora\GUM\autogum\autogum.git\nlp_modules\dep_parser.py", line 136, in predict_with_pos
    doc = self.nlp1(doc)
  File "C:\Uni\Corpora\GUM\autogum\autogum.git\stanfordnlp\pipeline\core.py", line 177, in __call__
    self.process(doc)
  File "C:\Uni\Corpora\GUM\autogum\autogum.git\stanfordnlp\pipeline\core.py", line 171, in process
    self.processors[processor_name].process(doc)
  File "C:\Uni\Corpora\GUM\autogum\autogum.git\stanfordnlp\pipeline\lemma_processor.py", line 66, in process
    ps, es = self.trainer.predict(b, self.config['beam_size'])
  File "C:\Uni\Corpora\GUM\autogum\autogum.git\stanfordnlp\models\lemma\trainer.py", line 88, in predict
    preds, edit_logits = self.model.predict(src, src_mask, pos=pos, beam_size=beam_size)
  File "C:\Uni\Corpora\GUM\autogum\autogum.git\stanfordnlp\models\common\seq2seq_model.py", line 206, in predict
    is_done = beam[b].advance(log_probs.data[b])
  File "C:\Uni\Corpora\GUM\autogum\autogum.git\stanfordnlp\models\common\beam.py", line 84, in advance
    prevK = bestScoresId / numWords
RuntimeError: Integer division of tensors using div or / is no longer supported, and in a future release div will perform true division as in Python 3. Use true_divide or floor_divide (// in Python) instead.
  0%|                                                                                                                                                                             | 0/4 [00:01<?, ?it/s]
```

Didn't we want to swap this out for Stanza? 

For xrenner I'll try retraining with transformers 3.5.1.

**Comment by lgessler** [comment]
> That trace actually looks like a different error, this time in transformers, not flair

right, it looks like some model that's being used was trained on an older version of transformers. let me try again with `transformers==3.0.2`

> Didn't we want to swap this out for Stanza?

yes, but nobody's done it yet. Are you on [`pytorch<1.6`](https://github.com/gucorpling/amalgum/blob/dev/requirements.txt#L21)? I think that's what that error you're getting is about

**Comment by amir-zeldes** [comment]
No, torch==1.6.0... But I want everything to be flush version wise, so I'll just try to upload a model with 3.5.1

**Comment by lgessler** [comment]
You should be on `torch<1.6`, not `torch==1.6`. In any case, yeah, assuming we're right about the cause we should update the models for the latest `transformers` anyway

**Comment by amir-zeldes** [comment]
Oh, wait, why? Which torch should I have then? It's happily training under torch 1.6 and transformers 3.5.1 as we speak...

**Comment by amir-zeldes** [comment]
So I'm now trying the latest before that, which is 1.5.1, and that's not on PyPI so I'm doing:

`pip install torch==1.5.1+cu101 -f https://download.pytorch.org/whl/torch_stable.html`

Seems the cu101 is needed for CUDA 10.1, which I'm using (let me know if you think that's an issue?)

**Comment by lgessler** [comment]
The error you're getting from `stanfordnlp` above is being caused by an API change in `pytorch>=1.6` that made calling a specific tensor operation an error instead of just a deprecation warning. Until we upgrade to `stanza` in our depparsing module we'll need to have `pytorch<1.6`  supported only. So yes, `pytorch==1.5.1` should be fine, and using the GPU or CPU flavor shouldn't matter.

**Comment by lgessler** [comment]
OK, I confirmed that downgrading to `transformers==3.0.2` resolved the xrenner issue I was having. After we confirm everything works again with our package updates I think it'd be good to put a tag at the HEAD of our dev branch (like v0.1.1) and rename all our model files to reflect this, e.g. `gum-pos-flair_v0.1.1.pt`

**Comment by lgessler** [comment]
...although now I'm getting an RST parser error:

```
2020-11-24 14:59:54,835 loading file /data/projects/amalgum/lib/dplp_plusplus/src/../models/rstdt_collapsed.pt
Load Brown clusters for creating features ...
INFO:root:Created directory target/08_RSTParser from target/07_FlairEDUSplitter.
INFO:root:Running module RSTParser
                                                                                                                                                                                                                                                     2020-11-24 14:59:55,204 loading file /data/projects/amalgum/lib/dplp_plusplus/src/../models/rstdt_collapsed.pt
ERROR:root:Encountered an error while processing file target/07_FlairEDUSplitter/tsv/autogum_academic_doc010.tsv!                                                                                                               | 0/1 [00:00<?, ?it/s]
  0%|                                                                                                                                                                                                                           | 0/1 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "nlp_controller.py", line 220, in <module>
    main()
  File "nlp_controller.py", line 215, in main
    controller.run()
  File "nlp_controller.py", line 132, in run
    module.run(input_dir, output_dir)
  File "/data/projects/amalgum/nlp_modules/rst_parser.py", line 76, in run
    self.process_files_multiformat(input_dir, output_dir, processing_function, multithreaded=False)
  File "/data/projects/amalgum/nlp_modules/base.py", line 257, in process_files_multiformat
    process_filename(filename)
  File "/data/projects/amalgum/nlp_modules/base.py", line 230, in process_filename
    raise e
  File "/data/projects/amalgum/nlp_modules/base.py", line 227, in process_filename
    output_dict = process_document_content_dict(content_dict)
  File "/data/projects/amalgum/nlp_modules/rst_parser.py", line 64, in parse
    fmerge = merge(doc_dict["rst"], doc_dict["xml"], doc_dict["dep"], doc_dict["filename"], seq=self.sequencer, as_text=True)
  File "/data/projects/amalgum/lib/dplp_plusplus/src/make_merge.py", line 128, in merge
    seq_preds = seq.predict_proba(edus)
  File "/data/projects/amalgum/lib/dplp_plusplus/src/make_merge.py", line 33, in predict_proba
    preds = self.tagger.predict(sentences)
  File "/home/luke/.anaconda3/envs/amalgum-test/lib/python3.7/site-packages/flair/models/text_classification_model.py", line 235, in predict
    scores, loss = self._forward_scores_and_loss(batch, return_loss)
  File "/home/luke/.anaconda3/envs/amalgum-test/lib/python3.7/site-packages/flair/models/text_classification_model.py", line 161, in _forward_scores_and_loss
    scores = self.forward(data_points)
  File "/home/luke/.anaconda3/envs/amalgum-test/lib/python3.7/site-packages/flair/models/text_classification_model.py", line 101, in forward
    self.document_embeddings.embed(sentences)
  File "/home/luke/.anaconda3/envs/amalgum-test/lib/python3.7/site-packages/flair/embeddings/base.py", line 55, in embed
    if self.name not in sentence._embeddings.keys():
AttributeError: 'str' object has no attribute '_embeddings'
  0%|                                                                                                                                                                                                                           | 0/1 [03:39<?, ?it/s]
  0%|                                                                                                                                                                                                                           | 0/1 [01:57<?, ?it/s]
  0%|                                                                                                                                                                                                                           | 0/1 [00:00<?, ?it/s]
```

**Comment by amir-zeldes** [comment]
OK, so I've replaced the model on corpling with one trained under flair 0.6.1, torch 1.5.1, transformers 3.5.1, which I understand is optimal (we think?). If you prefer the transformers 3.0.2 version, let me know and I can restore that one instead.

About this other error, I'm betting we just need to retrain this other model (looks like the RST-DT sequence labeler) with the same dependencies. Let me know which transformers you prefer and I'll update that model as well.

**Comment by lgessler** [comment]
Right, I think so. Let's stick with `transformers==3.5.1`

**Comment by amir-zeldes** [comment]
OK, training is complete, but surprisingly I'm still getting the same error locally:

```
ERROR:root:Encountered an error while processing file target\08_FlairEDUSplitter\xml\amalgum_academic_chemistry.xml!
  0%|                                                                                                                                                                             | 0/4 [00:00<?, ?it/s] Traceback (most recent call last):
  File "nlp_controller.py", line 220, in <module>
    main()
  File "nlp_controller.py", line 215, in main
    controller.run()
  File "nlp_controller.py", line 132, in run
    module.run(input_dir, output_dir)
  File "C:\Uni\Corpora\GUM\autogum\autogum.git\nlp_modules\rst_parser.py", line 76, in run
    self.process_files_multiformat(input_dir, output_dir, processing_function, multithreaded=False)
  File "C:\Uni\Corpora\GUM\autogum\autogum.git\nlp_modules\base.py", line 257, in process_files_multiformat
    process_filename(filename)
  File "C:\Uni\Corpora\GUM\autogum\autogum.git\nlp_modules\base.py", line 230, in process_filename
    raise e
  File "C:\Uni\Corpora\GUM\autogum\autogum.git\nlp_modules\base.py", line 227, in process_filename
    output_dict = process_document_content_dict(content_dict)
  File "C:\Uni\Corpora\GUM\autogum\autogum.git\nlp_modules\rst_parser.py", line 64, in parse
    fmerge = merge(doc_dict["rst"], doc_dict["xml"], doc_dict["dep"], doc_dict["filename"], seq=self.sequencer, as_text=True)
  File "C:\Uni\Corpora\GUM\autogum\autogum.git\lib\dplp_plusplus\src\make_merge.py", line 128, in merge
    seq_preds = seq.predict_proba(edus)
  File "C:\Uni\Corpora\GUM\autogum\autogum.git\lib\dplp_plusplus\src\make_merge.py", line 33, in predict_proba
    preds = self.tagger.predict(sentences)
  File "C:\Users\az364\AppData\Local\Programs\Python\Python38\lib\site-packages\flair\models\text_classification_model.py", line 223, in predict
    scores = self.forward(batch)
  File "C:\Users\az364\AppData\Local\Programs\Python\Python38\lib\site-packages\flair\models\text_classification_model.py", line 99, in forward
    self.document_embeddings.embed(sentences)
  File "C:\Users\az364\AppData\Local\Programs\Python\Python38\lib\site-packages\flair\embeddings\base.py", line 55, in embed
    if self.name not in sentence._embeddings.keys():
AttributeError: 'str' object has no attribute '_embeddings'
```

What's strange about this is that the model was trained using the exact same Python, flair, transformers etc., which is 0.6.1, 3.5.1 etc. I can't actually find mentions of this error online, so any ideas are appreciated. The model is on corpling in amalgum/rst/ - does it run for you?

BTW it uses flair embeddings + char embeddings, so I could try switching to BERT like xrenner, but it uses flair's sentence classifier API (not token-wise tagging), so it's not 1:1 the same as the working model from xrenner.

**Comment by lgessler** [comment]
Hm, I get the same error. Does dplp++ depend on any serialized models? Perhaps we have old versions of the flair embeddings cached?

**Comment by amir-zeldes** [comment]
Yes, DPLP++ involves several serialized models, but only one if flair, which is the sequence classifier trained on RST-DT which predicts a categorical label from the collapsed RST-DT set for each EDU. This is then used as a feature for the actual DPLP++ shift-reduce classifier.

The old flair embeddings hypothesis sounded promising, so I tested it, but no dice: I deleted the flair embeddings, re-downloaded, trained on flair 0.6.1 again, and the error message is the same. I'll tinker with getting the model's predict method to work in isolation outside nlp_controller for a bit, and if not I'll try another embeddings framework (a naive run with Distilbert just produced much lower scores though, so I suspect hyperparameters need to be changed from the values I found here: https://github.com/flairNLP/flair/blob/master/resources/docs/TUTORIAL_7_TRAINING_A_MODEL.md)

**Comment by amir-zeldes** [comment]
Jackpot - it was just the same incompatibility that xrenner had to solve, where inputs to flair 0.6.1 need to be wrapped in Sentence() objects. As of 462de8a I can get the entire pipeline to run on my PC, with the flair based RST-DT model. 

I also played around with Distilbert and got it to competitive scores, but still 2 points below flair, so I'd stick with the model now on corpling. @lgessler can you pull from dev and reproduce a successful run with the current public models on your machine?

**Comment by lgessler** [comment]
Yup, looks like we're in good shape now. I've ensured [env.yml](https://github.com/gucorpling/amalgum/blob/dev/env.yml) and [requirements.txt](https://github.com/gucorpling/amalgum/blob/dev/requirements.txt) are up to date now.

Next, I think we should version our models (`xyz.pt` => `xyz_0.2.pt`), update all references to our models in the code, and then merge this into master and tag it v0.2 so we can have a solid foundation moving forward.
